### ISSUE TITLE
Structure, General Rules for Code/Repos

### ISSUE THREAD

**Issue by jdsika** [openMSL/governance-and-documentation#1]
Create separate markdown files for each data cluster. In addtioion to the rules of OpenMSL with its paragraphs there must be also a section for coding guidelines that must be applied for all projects like e.g. [using SPDX](https://spdx.dev/resources/use/).

**Comment by jdsika** [comment]
As there is already a double licensing in place I would suggest to remove the EUPL license and continue only under the MPL 2.0 as it simplifies the overall structure.

**Comment by jdsika** [comment]
Add best practices for CCBs. How often do they meet. Do they have a email list. Create tag "ready for CCB" (as we know it from ASAM)

**Comment by jdsika** [comment]
Overleaf integration and latex ci pipeline evaluation.

**Comment by ClemensLinnhoff** [comment]
> Create separate markdown files for each data cluster. In addtioion to the rules of OpenMSL with its paragraphs there must be also a section for coding guidelines that must be applied for all projects like e.g. [using SPDX](https://spdx.dev/resources/use/).

The use of SPDX identifiers was decided in today's DCM meeting. A prototypical implementation was proposed as a PR in the [reflection based lidar model](https://github.com/openMSL/reflection_based_lidar_object_model).


> As there is already a double licensing in place I would suggest to remove the EUPL license and continue only under the MPL 2.0 as it simplifies the overall structure.

This was also decided and prototypically implemented in the same model.



> Add best practices for CCBs. How often do they meet. Do they have a email list. Create tag "ready for CCB" (as we know it from ASAM)

The labels "ready for maintainer review" and "ready to merge" were introduced in the model, a unified labeling for the entire data cluster needs to be further discussed in the next meeting.

**Comment by ClemensLinnhoff** [comment]
Another topic for the next meeting is a naming scheme for the repositories, as well as the documentation language (latex, markdown or other).
