### ISSUE TITLE
Documentation: Repository naming and tags

### ISSUE THREAD

**Issue by ClemensLinnhoff** [openMSL/governance-and-documentation#4]
Requirements
- Readability
- Consistency: name and link
- Interface agnostic inputs and output description
- Unique identifier within organization/project
- Harmonization with ISO 11010-2

**Comment by LukasElster** [comment]
So far the taxonomy defined in the workgroup is:

Model Type <IR> / <CM> / <MF> / <CF> / <OR>

where

- <IR> is Input Resolution
- <CM> is Channel Model
- <MF> is Model Fidelity
- <CF> is Controller Fidelity
- <OR> is Output Resolution

Each Placeholder is replaced with a number which has a defined meaning. Video Camera (VM), Radar (RM), Lidar (LM) and none technology specific sensor models (xM) would be inserted for the model type.

Therefore a classification of our radar model would look like

- RM 3 / 2 / 3 / 2 / 1

or if we don't take the numbers but the corresponding meaning out of the ISO, then it would look like

RM Reflection / Integrated in sensor model / Phenomenological / SiL, Target ASW / Object

Details regarding the number's meaning I will share in the next DCM Meeting.

**Comment by jdsika** [comment]
I would propose to use these as `tags` in the meta data of the model and not as naming scheme?

[IR3]

We would be flexible regarding changes of the tags and could search and sort by it.

**Comment by jdsika** [comment]
As we discussed in #6 we would rename `Data Cluster` to `Sub Library`. The naming scheme could be:
prefix: `sl`
id of sub library cont.: `1`
id of repository of sl cont.: `1`
OSI input: `object-based`
technology: `radar`
OSI output: ´object-model`

Everything in small letters with `-` as spacing.

Resul: `sl-1-1-object-based-radar-objekt-model`

**Comment by ClemensLinnhoff** [comment]
The general naming scheme was developed in the setlevel project and published here: https://tuprints.ulb.tu-darmstadt.de/18672/1/2020_ATZ_Object_Model.pdf

**Comment by jdsika** [comment]
TODO: Create section in the docs explaining the naming schema @ClemensLinnhoff
